// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/JVM.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PoolType int32

const (
	PoolType_CODE_CACHE_USAGE PoolType = 0
	PoolType_NEWGEN_USAGE     PoolType = 1
	PoolType_OLDGEN_USAGE     PoolType = 2
	PoolType_SURVIVOR_USAGE   PoolType = 3
	PoolType_PERMGEN_USAGE    PoolType = 4
	PoolType_METASPACE_USAGE  PoolType = 5
)

var PoolType_name = map[int32]string{
	0: "CODE_CACHE_USAGE",
	1: "NEWGEN_USAGE",
	2: "OLDGEN_USAGE",
	3: "SURVIVOR_USAGE",
	4: "PERMGEN_USAGE",
	5: "METASPACE_USAGE",
}

var PoolType_value = map[string]int32{
	"CODE_CACHE_USAGE": 0,
	"NEWGEN_USAGE":     1,
	"OLDGEN_USAGE":     2,
	"SURVIVOR_USAGE":   3,
	"PERMGEN_USAGE":    4,
	"METASPACE_USAGE":  5,
}

func (x PoolType) String() string {
	return proto.EnumName(PoolType_name, int32(x))
}

func (PoolType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_42f5f61b58cf3158, []int{0}
}

type GCPhrase int32

const (
	GCPhrase_NEW GCPhrase = 0
	GCPhrase_OLD GCPhrase = 1
)

var GCPhrase_name = map[int32]string{
	0: "NEW",
	1: "OLD",
}

var GCPhrase_value = map[string]int32{
	"NEW": 0,
	"OLD": 1,
}

func (x GCPhrase) String() string {
	return proto.EnumName(GCPhrase_name, int32(x))
}

func (GCPhrase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_42f5f61b58cf3158, []int{1}
}

type JVMMetric struct {
	EnvCode              string        `protobuf:"bytes,1,opt,name=envCode,proto3" json:"envCode,omitempty"`
	Time                 int64         `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Cpu                  *CPU          `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory               []*Memory     `protobuf:"bytes,4,rep,name=memory,proto3" json:"memory,omitempty"`
	MemoryPool           []*MemoryPool `protobuf:"bytes,5,rep,name=memoryPool,proto3" json:"memoryPool,omitempty"`
	Gc                   []*GC         `protobuf:"bytes,6,rep,name=gc,proto3" json:"gc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *JVMMetric) Reset()         { *m = JVMMetric{} }
func (m *JVMMetric) String() string { return proto.CompactTextString(m) }
func (*JVMMetric) ProtoMessage()    {}
func (*JVMMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_42f5f61b58cf3158, []int{0}
}

func (m *JVMMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JVMMetric.Unmarshal(m, b)
}
func (m *JVMMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JVMMetric.Marshal(b, m, deterministic)
}
func (m *JVMMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JVMMetric.Merge(m, src)
}
func (m *JVMMetric) XXX_Size() int {
	return xxx_messageInfo_JVMMetric.Size(m)
}
func (m *JVMMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_JVMMetric.DiscardUnknown(m)
}

var xxx_messageInfo_JVMMetric proto.InternalMessageInfo

func (m *JVMMetric) GetEnvCode() string {
	if m != nil {
		return m.EnvCode
	}
	return ""
}

func (m *JVMMetric) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *JVMMetric) GetCpu() *CPU {
	if m != nil {
		return m.Cpu
	}
	return nil
}

func (m *JVMMetric) GetMemory() []*Memory {
	if m != nil {
		return m.Memory
	}
	return nil
}

func (m *JVMMetric) GetMemoryPool() []*MemoryPool {
	if m != nil {
		return m.MemoryPool
	}
	return nil
}

func (m *JVMMetric) GetGc() []*GC {
	if m != nil {
		return m.Gc
	}
	return nil
}

type Memory struct {
	IsHeap               bool     `protobuf:"varint,1,opt,name=isHeap,proto3" json:"isHeap,omitempty"`
	Init                 int64    `protobuf:"varint,2,opt,name=init,proto3" json:"init,omitempty"`
	Max                  int64    `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	Used                 int64    `protobuf:"varint,4,opt,name=used,proto3" json:"used,omitempty"`
	Committed            int64    `protobuf:"varint,5,opt,name=committed,proto3" json:"committed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Memory) Reset()         { *m = Memory{} }
func (m *Memory) String() string { return proto.CompactTextString(m) }
func (*Memory) ProtoMessage()    {}
func (*Memory) Descriptor() ([]byte, []int) {
	return fileDescriptor_42f5f61b58cf3158, []int{1}
}

func (m *Memory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Memory.Unmarshal(m, b)
}
func (m *Memory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Memory.Marshal(b, m, deterministic)
}
func (m *Memory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Memory.Merge(m, src)
}
func (m *Memory) XXX_Size() int {
	return xxx_messageInfo_Memory.Size(m)
}
func (m *Memory) XXX_DiscardUnknown() {
	xxx_messageInfo_Memory.DiscardUnknown(m)
}

var xxx_messageInfo_Memory proto.InternalMessageInfo

func (m *Memory) GetIsHeap() bool {
	if m != nil {
		return m.IsHeap
	}
	return false
}

func (m *Memory) GetInit() int64 {
	if m != nil {
		return m.Init
	}
	return 0
}

func (m *Memory) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *Memory) GetUsed() int64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *Memory) GetCommitted() int64 {
	if m != nil {
		return m.Committed
	}
	return 0
}

type MemoryPool struct {
	Type                 PoolType `protobuf:"varint,1,opt,name=type,proto3,enum=PoolType" json:"type,omitempty"`
	Init                 int64    `protobuf:"varint,2,opt,name=init,proto3" json:"init,omitempty"`
	Max                  int64    `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	Used                 int64    `protobuf:"varint,4,opt,name=used,proto3" json:"used,omitempty"`
	Commited             int64    `protobuf:"varint,5,opt,name=commited,proto3" json:"commited,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryPool) Reset()         { *m = MemoryPool{} }
func (m *MemoryPool) String() string { return proto.CompactTextString(m) }
func (*MemoryPool) ProtoMessage()    {}
func (*MemoryPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_42f5f61b58cf3158, []int{2}
}

func (m *MemoryPool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryPool.Unmarshal(m, b)
}
func (m *MemoryPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryPool.Marshal(b, m, deterministic)
}
func (m *MemoryPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryPool.Merge(m, src)
}
func (m *MemoryPool) XXX_Size() int {
	return xxx_messageInfo_MemoryPool.Size(m)
}
func (m *MemoryPool) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryPool.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryPool proto.InternalMessageInfo

func (m *MemoryPool) GetType() PoolType {
	if m != nil {
		return m.Type
	}
	return PoolType_CODE_CACHE_USAGE
}

func (m *MemoryPool) GetInit() int64 {
	if m != nil {
		return m.Init
	}
	return 0
}

func (m *MemoryPool) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *MemoryPool) GetUsed() int64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *MemoryPool) GetCommited() int64 {
	if m != nil {
		return m.Commited
	}
	return 0
}

type GC struct {
	Phrase               GCPhrase `protobuf:"varint,1,opt,name=phrase,proto3,enum=GCPhrase" json:"phrase,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Time                 int64    `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GC) Reset()         { *m = GC{} }
func (m *GC) String() string { return proto.CompactTextString(m) }
func (*GC) ProtoMessage()    {}
func (*GC) Descriptor() ([]byte, []int) {
	return fileDescriptor_42f5f61b58cf3158, []int{3}
}

func (m *GC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GC.Unmarshal(m, b)
}
func (m *GC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GC.Marshal(b, m, deterministic)
}
func (m *GC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GC.Merge(m, src)
}
func (m *GC) XXX_Size() int {
	return xxx_messageInfo_GC.Size(m)
}
func (m *GC) XXX_DiscardUnknown() {
	xxx_messageInfo_GC.DiscardUnknown(m)
}

var xxx_messageInfo_GC proto.InternalMessageInfo

func (m *GC) GetPhrase() GCPhrase {
	if m != nil {
		return m.Phrase
	}
	return GCPhrase_NEW
}

func (m *GC) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GC) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterEnum("PoolType", PoolType_name, PoolType_value)
	proto.RegisterEnum("GCPhrase", GCPhrase_name, GCPhrase_value)
	proto.RegisterType((*JVMMetric)(nil), "JVMMetric")
	proto.RegisterType((*Memory)(nil), "Memory")
	proto.RegisterType((*MemoryPool)(nil), "MemoryPool")
	proto.RegisterType((*GC)(nil), "GC")
}

func init() {
	proto.RegisterFile("common/JVM.proto", fileDescriptor_42f5f61b58cf3158)
}

var fileDescriptor_42f5f61b58cf3158 = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xcd, 0x6e, 0xda, 0x4e,
	0x14, 0xc5, 0xe3, 0x0f, 0x0c, 0x5c, 0xfe, 0xff, 0xd4, 0x1d, 0xa2, 0xc8, 0x42, 0xa9, 0x4a, 0x59,
	0xa1, 0x54, 0x35, 0x15, 0xed, 0x0b, 0x50, 0x63, 0x91, 0x46, 0x18, 0xdc, 0x21, 0x80, 0xd4, 0x4d,
	0x64, 0xcc, 0xc8, 0x58, 0x60, 0x8f, 0x65, 0x8f, 0x9b, 0x78, 0xd7, 0xae, 0xfa, 0x2e, 0x5d, 0xf7,
	0x01, 0xab, 0xf1, 0x07, 0xee, 0xbe, 0x2b, 0x9f, 0xfb, 0x9b, 0xa3, 0x7b, 0x8f, 0x67, 0x74, 0x41,
	0x75, 0x69, 0x10, 0xd0, 0x70, 0x74, 0xbf, 0xb1, 0xf4, 0x28, 0xa6, 0x8c, 0xf6, 0xba, 0x25, 0x29,
	0x3e, 0x05, 0x1c, 0xfc, 0x16, 0xa0, 0x7d, 0xbf, 0xb1, 0x2c, 0xc2, 0x62, 0xdf, 0x45, 0x1a, 0x34,
	0x49, 0xf8, 0xcd, 0xa0, 0x7b, 0xa2, 0x09, 0x7d, 0x61, 0xd8, 0xc6, 0x55, 0x89, 0x10, 0xc8, 0xcc,
	0x0f, 0x88, 0x26, 0xf6, 0x85, 0xa1, 0x84, 0x73, 0x8d, 0xae, 0x41, 0x72, 0xa3, 0x54, 0x93, 0xfa,
	0xc2, 0xb0, 0x33, 0x96, 0x75, 0xc3, 0x5e, 0x63, 0x0e, 0xd0, 0x6b, 0x50, 0x02, 0x12, 0xd0, 0x38,
	0xd3, 0xe4, 0xbe, 0x34, 0xec, 0x8c, 0x9b, 0xba, 0x95, 0x97, 0xb8, 0xc4, 0xe8, 0x2d, 0x40, 0xa1,
	0x6c, 0x4a, 0x4f, 0x5a, 0x23, 0x37, 0x75, 0x4a, 0x13, 0x47, 0xf8, 0xaf, 0x63, 0xd4, 0x05, 0xd1,
	0x73, 0x35, 0x25, 0x37, 0x49, 0xfa, 0xcc, 0xc0, 0xa2, 0xe7, 0x0e, 0x9e, 0x41, 0x29, 0xec, 0xe8,
	0x1a, 0x14, 0x3f, 0xb9, 0x23, 0x4e, 0x94, 0x27, 0x6e, 0xe1, 0xb2, 0xe2, 0x81, 0xfd, 0xd0, 0x67,
	0x55, 0x60, 0xae, 0x91, 0x0a, 0x52, 0xe0, 0x3c, 0xe7, 0x81, 0x25, 0xcc, 0x25, 0x77, 0xa5, 0x09,
	0xd9, 0x6b, 0x72, 0xe1, 0xe2, 0x1a, 0xdd, 0x40, 0x9b, 0x5f, 0x91, 0xcf, 0x18, 0xd9, 0x6b, 0x8d,
	0xfc, 0xa0, 0x06, 0x83, 0x1f, 0x02, 0x40, 0x9d, 0x14, 0xbd, 0x02, 0x99, 0x65, 0x51, 0x71, 0x5d,
	0x97, 0xe3, 0xb6, 0xce, 0xe1, 0x43, 0x16, 0x11, 0x9c, 0xe3, 0x7f, 0x48, 0xd1, 0x83, 0x56, 0x31,
	0xf4, 0x1c, 0xe2, 0x5c, 0x0f, 0xbe, 0x80, 0x38, 0x33, 0xd0, 0x1b, 0x50, 0xa2, 0x43, 0xec, 0x24,
	0xf5, 0xf0, 0x99, 0x61, 0xe7, 0x00, 0x97, 0x07, 0xe8, 0x0a, 0x1a, 0x2e, 0x4d, 0xc3, 0x6a, 0x7e,
	0x51, 0x9c, 0xdf, 0x52, 0xaa, 0xdf, 0xf2, 0xf6, 0xbb, 0x00, 0xad, 0x2a, 0x3b, 0xba, 0x02, 0xd5,
	0x58, 0x4e, 0xcd, 0x47, 0x63, 0x62, 0xdc, 0x99, 0x8f, 0xeb, 0xd5, 0x64, 0x66, 0xaa, 0x17, 0x48,
	0x85, 0xff, 0x16, 0xe6, 0x76, 0x66, 0x2e, 0x4a, 0x22, 0x70, 0xb2, 0x9c, 0x4f, 0x6b, 0x22, 0x22,
	0x04, 0x97, 0xab, 0x35, 0xde, 0x7c, 0xde, 0x2c, 0x71, 0xc9, 0x24, 0xf4, 0x12, 0xfe, 0xb7, 0x4d,
	0x6c, 0xd5, 0x36, 0x19, 0x75, 0xe1, 0x85, 0x65, 0x3e, 0x4c, 0x56, 0xf6, 0xc4, 0xa8, 0xfa, 0x37,
	0x6e, 0x6f, 0xa0, 0x55, 0xfd, 0x00, 0x6a, 0x82, 0xb4, 0x30, 0xb7, 0xea, 0x05, 0x17, 0xcb, 0xf9,
	0x54, 0x15, 0x3e, 0xfd, 0x14, 0xe0, 0x3d, 0x8d, 0x3d, 0xdd, 0x89, 0x1c, 0xf7, 0x40, 0xf4, 0xe4,
	0x98, 0x3d, 0x39, 0xa7, 0xa3, 0x1f, 0x72, 0x12, 0xe8, 0x21, 0x61, 0x4f, 0x34, 0x3e, 0xea, 0x27,
	0x27, 0xf4, 0x52, 0xc7, 0x23, 0xba, 0xe3, 0x91, 0x90, 0xd9, 0xc2, 0xd7, 0x8f, 0x9e, 0xcf, 0x0e,
	0xe9, 0x4e, 0x77, 0x69, 0x30, 0x9a, 0x3a, 0xd4, 0x38, 0xd1, 0x74, 0xff, 0x6e, 0xee, 0xec, 0x92,
	0x91, 0x47, 0xc7, 0xc9, 0x31, 0x1b, 0xc5, 0x24, 0xa2, 0x31, 0x23, 0xf1, 0xc8, 0x8b, 0x23, 0xb7,
	0xdc, 0x8d, 0x5f, 0x62, 0x6f, 0x75, 0xcc, 0xb6, 0x65, 0xff, 0x45, 0xd1, 0xdb, 0xe6, 0xfb, 0xe2,
	0xd2, 0xd3, 0x4e, 0xc9, 0x37, 0xe7, 0xc3, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x38, 0x2b,
	0x2a, 0x62, 0x03, 0x00, 0x00,
}
