// Code generated by protoc-gen-go. DO NOT EDIT.
// source: register/InstancePing.proto

package register

import (
	context "context"
	fmt "fmt"
	common "github.com/DaoCloud-Labs/go2sky/reporter/grpc/common"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServiceInstancePingPkg struct {
	EnvCode              string   `protobuf:"bytes,1,opt,name=envCode,proto3" json:"envCode,omitempty"`
	ServiceInstanceId    int32    `protobuf:"varint,2,opt,name=serviceInstanceId,proto3" json:"serviceInstanceId,omitempty"`
	Time                 int64    `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	ServiceInstanceUUID  string   `protobuf:"bytes,4,opt,name=serviceInstanceUUID,proto3" json:"serviceInstanceUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceInstancePingPkg) Reset()         { *m = ServiceInstancePingPkg{} }
func (m *ServiceInstancePingPkg) String() string { return proto.CompactTextString(m) }
func (*ServiceInstancePingPkg) ProtoMessage()    {}
func (*ServiceInstancePingPkg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c10bfdff83d834ed, []int{0}
}

func (m *ServiceInstancePingPkg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInstancePingPkg.Unmarshal(m, b)
}
func (m *ServiceInstancePingPkg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInstancePingPkg.Marshal(b, m, deterministic)
}
func (m *ServiceInstancePingPkg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInstancePingPkg.Merge(m, src)
}
func (m *ServiceInstancePingPkg) XXX_Size() int {
	return xxx_messageInfo_ServiceInstancePingPkg.Size(m)
}
func (m *ServiceInstancePingPkg) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInstancePingPkg.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInstancePingPkg proto.InternalMessageInfo

func (m *ServiceInstancePingPkg) GetEnvCode() string {
	if m != nil {
		return m.EnvCode
	}
	return ""
}

func (m *ServiceInstancePingPkg) GetServiceInstanceId() int32 {
	if m != nil {
		return m.ServiceInstanceId
	}
	return 0
}

func (m *ServiceInstancePingPkg) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ServiceInstancePingPkg) GetServiceInstanceUUID() string {
	if m != nil {
		return m.ServiceInstanceUUID
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceInstancePingPkg)(nil), "ServiceInstancePingPkg")
}

func init() {
	proto.RegisterFile("register/InstancePing.proto", fileDescriptor_c10bfdff83d834ed)
}

var fileDescriptor_c10bfdff83d834ed = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0xcd, 0x36, 0x27, 0xcb, 0xcd, 0x0c, 0xb4, 0xcc, 0xcb, 0xd8, 0x69, 0x07, 0x97, 0xc8,
	0x04, 0x3f, 0x80, 0x9b, 0x87, 0x81, 0x48, 0xd9, 0x18, 0x82, 0xb7, 0x2c, 0x0d, 0x59, 0xc9, 0x92,
	0xb7, 0x24, 0x59, 0x47, 0xbf, 0x80, 0x1f, 0xc5, 0x83, 0x9f, 0x52, 0xda, 0x5a, 0xf0, 0x4f, 0x4f,
	0x79, 0x92, 0x27, 0xcf, 0x93, 0xbc, 0x3f, 0x7c, 0xe3, 0xa4, 0x4a, 0x7d, 0x90, 0x8e, 0xad, 0xac,
	0x0f, 0xdc, 0x0a, 0x19, 0xa7, 0x56, 0xd1, 0xcc, 0x41, 0x80, 0xd1, 0x50, 0x80, 0x31, 0x60, 0x59,
	0xbd, 0xd4, 0x87, 0x93, 0x0f, 0x84, 0xaf, 0x36, 0xd2, 0xe5, 0xa9, 0x90, 0x3f, 0x23, 0xb1, 0x56,
	0x24, 0xc2, 0x17, 0xd2, 0xe6, 0x0b, 0x48, 0x64, 0x84, 0xc6, 0x68, 0x3a, 0x58, 0x37, 0x5b, 0x72,
	0x8b, 0x2f, 0xfd, 0xef, 0xcc, 0x2a, 0x89, 0x3a, 0x63, 0x34, 0x3d, 0x5f, 0xff, 0x37, 0x08, 0xc1,
	0xbd, 0x90, 0x1a, 0x19, 0x75, 0xc7, 0x68, 0xda, 0x5d, 0x57, 0x9a, 0xdc, 0xe1, 0xe1, 0x9f, 0x8b,
	0xdb, 0xed, 0x6a, 0x19, 0xf5, 0xaa, 0x77, 0xda, 0xac, 0xf9, 0x13, 0x1e, 0xb6, 0xfc, 0x93, 0x50,
	0xdc, 0x4f, 0xa0, 0x52, 0xd7, 0xb4, 0x7d, 0x8e, 0xd1, 0x80, 0x2e, 0xc0, 0x18, 0x6e, 0x13, 0x3f,
	0x39, 0x7b, 0x7c, 0x47, 0x78, 0x06, 0x4e, 0x51, 0x9e, 0x71, 0xb1, 0x97, 0xd4, 0xeb, 0xe2, 0xc4,
	0x0f, 0xba, 0x84, 0xc4, 0x33, 0x43, 0xad, 0x0c, 0x27, 0x70, 0x9a, 0x36, 0x18, 0x69, 0x3e, 0x8f,
	0xd1, 0xdb, 0x83, 0x4a, 0xc3, 0xfe, 0xb8, 0xa3, 0x02, 0x0c, 0x5b, 0x72, 0x58, 0x1c, 0xe0, 0x98,
	0xcc, 0x9e, 0xf9, 0xce, 0x33, 0x05, 0x73, 0xaf, 0x0b, 0xe6, 0x64, 0x06, 0xae, 0xa4, 0xae, 0x5c,
	0x26, 0x58, 0x13, 0xfe, 0xec, 0x8c, 0x36, 0xba, 0x78, 0xfd, 0xae, 0x7f, 0xa9, 0xab, 0xe3, 0x92,
	0xba, 0x80, 0xc3, 0xae, 0x5f, 0xf1, 0xbf, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x6a, 0xfa, 0xeb,
	0x6f, 0xb3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServiceInstancePingClient is the client API for ServiceInstancePing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceInstancePingClient interface {
	DoPing(ctx context.Context, in *ServiceInstancePingPkg, opts ...grpc.CallOption) (*common.Commands, error)
}

type serviceInstancePingClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceInstancePingClient(cc grpc.ClientConnInterface) ServiceInstancePingClient {
	return &serviceInstancePingClient{cc}
}

func (c *serviceInstancePingClient) DoPing(ctx context.Context, in *ServiceInstancePingPkg, opts ...grpc.CallOption) (*common.Commands, error) {
	out := new(common.Commands)
	err := c.cc.Invoke(ctx, "/ServiceInstancePing/doPing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceInstancePingServer is the server API for ServiceInstancePing service.
type ServiceInstancePingServer interface {
	DoPing(context.Context, *ServiceInstancePingPkg) (*common.Commands, error)
}

// UnimplementedServiceInstancePingServer can be embedded to have forward compatible implementations.
type UnimplementedServiceInstancePingServer struct {
}

func (*UnimplementedServiceInstancePingServer) DoPing(ctx context.Context, req *ServiceInstancePingPkg) (*common.Commands, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoPing not implemented")
}

func RegisterServiceInstancePingServer(s *grpc.Server, srv ServiceInstancePingServer) {
	s.RegisterService(&_ServiceInstancePing_serviceDesc, srv)
}

func _ServiceInstancePing_DoPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInstancePingPkg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceInstancePingServer).DoPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ServiceInstancePing/DoPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceInstancePingServer).DoPing(ctx, req.(*ServiceInstancePingPkg))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceInstancePing_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ServiceInstancePing",
	HandlerType: (*ServiceInstancePingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "doPing",
			Handler:    _ServiceInstancePing_DoPing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "register/InstancePing.proto",
}
